---

name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      -
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: install
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}-${{ github.sha }}
            ${{ github.ref }}
            refs/heads/main
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ginou-automata
          export_default_credentials: true
          service_account_key: ${{ secrets.BASE64_ENCODED_GOOGLE_SERVICE_ACCOUNT_KEY }}
      # refs. https://github.com/google-github-actions/setup-gcloud/issues/330
      - name: install beta components
        run: gcloud components install beta
      - name: configure docker
        run: gcloud auth configure-docker --quiet
      - name: docker build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: asia.gcr.io/ginou-automata/ginou-automata/ginou-automata-app:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: deploy to Cloud Run
        run: |
          gcloud beta run services update ginou-automata-app \
            --platform=managed \
            --image=asia.gcr.io/ginou-automata/ginou-automata/ginou-automata-app:${{ github.sha }} \
            --region=asia-east1 \
            --labels=commit-sha=${{ github.sha }},gh-actions-job-id=${{ github.job }} \
            --set-env-vars=GOOGLE_CLOUD_PROJECT=ginou-automata \
            --set-secrets=GINOU_LOGIN_ID=GINOU_LOGIN_ID:latest,GINOU_LOGIN_PASSWORD=GINOU_LOGIN_PASSWORD:latest,GINOU_YOYAKU_URL=GINOU_YOYAKU_URL:latest \
            --service-account=cloud-run-runner@ginou-automata.iam.gserviceaccount.com \
            --memory=2Gi \
            --quiet
